// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.0
// - protoc             v5.29.3
// source: api/service/v1alpha1/service.proto

package v1alpha1

import (
	context "context"
	common "github.com/f-rambo/cloud-copilot/api/common"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationServiceInterfaceApplyService = "/service.v1alpha1.ServiceInterface/ApplyService"
const OperationServiceInterfaceCreateContinuousDeployment = "/service.v1alpha1.ServiceInterface/CreateContinuousDeployment"
const OperationServiceInterfaceCreateContinuousIntegration = "/service.v1alpha1.ServiceInterface/CreateContinuousIntegration"
const OperationServiceInterfaceDelete = "/service.v1alpha1.ServiceInterface/Delete"
const OperationServiceInterfaceDeleteContinuousDeployment = "/service.v1alpha1.ServiceInterface/DeleteContinuousDeployment"
const OperationServiceInterfaceDeleteContinuousIntegration = "/service.v1alpha1.ServiceInterface/DeleteContinuousIntegration"
const OperationServiceInterfaceGet = "/service.v1alpha1.ServiceInterface/Get"
const OperationServiceInterfaceGetContinuousDeployment = "/service.v1alpha1.ServiceInterface/GetContinuousDeployment"
const OperationServiceInterfaceGetContinuousDeployments = "/service.v1alpha1.ServiceInterface/GetContinuousDeployments"
const OperationServiceInterfaceGetContinuousIntegration = "/service.v1alpha1.ServiceInterface/GetContinuousIntegration"
const OperationServiceInterfaceGetContinuousIntegrations = "/service.v1alpha1.ServiceInterface/GetContinuousIntegrations"
const OperationServiceInterfaceGetServiceWorkflow = "/service.v1alpha1.ServiceInterface/GetServiceWorkflow"
const OperationServiceInterfaceList = "/service.v1alpha1.ServiceInterface/List"
const OperationServiceInterfaceSave = "/service.v1alpha1.ServiceInterface/Save"
const OperationServiceInterfaceSaveServiceWorkflow = "/service.v1alpha1.ServiceInterface/SaveServiceWorkflow"

type ServiceInterfaceHTTPServer interface {
	ApplyService(context.Context, *ApplyServiceRequest) (*common.Msg, error)
	CreateContinuousDeployment(context.Context, *ContinuousDeployment) (*common.Msg, error)
	CreateContinuousIntegration(context.Context, *ContinuousIntegration) (*common.Msg, error)
	Delete(context.Context, *ServiceDetailIdRequest) (*common.Msg, error)
	DeleteContinuousDeployment(context.Context, *ContinuousDeploymentDetailRequest) (*common.Msg, error)
	DeleteContinuousIntegration(context.Context, *ContinuousIntegrationDetailRequest) (*common.Msg, error)
	Get(context.Context, *ServiceDetailIdRequest) (*Service, error)
	GetContinuousDeployment(context.Context, *ContinuousDeploymentDetailRequest) (*ContinuousDeployment, error)
	GetContinuousDeployments(context.Context, *ContinuousDeploymentsRequest) (*ContinuousDeployments, error)
	GetContinuousIntegration(context.Context, *ContinuousIntegrationDetailRequest) (*ContinuousIntegration, error)
	GetContinuousIntegrations(context.Context, *ContinuousIntegrationsRequest) (*ContinuousIntegrations, error)
	GetServiceWorkflow(context.Context, *GetServiceWorkflowRequest) (*Workflow, error)
	List(context.Context, *ServicesRequest) (*Services, error)
	Save(context.Context, *Service) (*common.Msg, error)
	SaveServiceWorkflow(context.Context, *Workflow) (*common.Msg, error)
}

func RegisterServiceInterfaceHTTPServer(s *http.Server, srv ServiceInterfaceHTTPServer) {
	r := s.Route("/")
	r.GET("/api/v1alpha1/service/list", _ServiceInterface_List4_HTTP_Handler(srv))
	r.POST("/api/v1alpha1/service", _ServiceInterface_Save4_HTTP_Handler(srv))
	r.GET("/api/v1alpha1/service", _ServiceInterface_Get4_HTTP_Handler(srv))
	r.DELETE("/api/v1alpha1/service", _ServiceInterface_Delete4_HTTP_Handler(srv))
	r.POST("/api/v1alpha1/service/workflow", _ServiceInterface_SaveServiceWorkflow0_HTTP_Handler(srv))
	r.GET("/api/v1alpha1/service/workflow", _ServiceInterface_GetServiceWorkflow0_HTTP_Handler(srv))
	r.POST("/api/v1alpha1/service/continuousintegration", _ServiceInterface_CreateContinuousIntegration0_HTTP_Handler(srv))
	r.GET("/api/v1alpha1/service/continuousintegration", _ServiceInterface_GetContinuousIntegration0_HTTP_Handler(srv))
	r.GET("/api/v1alpha1/service/continuousintegrations", _ServiceInterface_GetContinuousIntegrations0_HTTP_Handler(srv))
	r.DELETE("/api/v1alpha1/service/continuousintegration", _ServiceInterface_DeleteContinuousIntegration0_HTTP_Handler(srv))
	r.POST("/api/v1alpha1/service/continuousdeployment", _ServiceInterface_CreateContinuousDeployment0_HTTP_Handler(srv))
	r.GET("/api/v1alpha1/service/continuousdeployment", _ServiceInterface_GetContinuousDeployment0_HTTP_Handler(srv))
	r.GET("/api/v1alpha1/service/continuousdeployments", _ServiceInterface_GetContinuousDeployments0_HTTP_Handler(srv))
	r.DELETE("/api/v1alpha1/service/continuousdeployment", _ServiceInterface_DeleteContinuousDeployment0_HTTP_Handler(srv))
	r.POST("/api/v1alpha1/service/apply", _ServiceInterface_ApplyService0_HTTP_Handler(srv))
}

func _ServiceInterface_List4_HTTP_Handler(srv ServiceInterfaceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ServicesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationServiceInterfaceList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.List(ctx, req.(*ServicesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Services)
		return ctx.Result(200, reply)
	}
}

func _ServiceInterface_Save4_HTTP_Handler(srv ServiceInterfaceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in Service
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationServiceInterfaceSave)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Save(ctx, req.(*Service))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*common.Msg)
		return ctx.Result(200, reply)
	}
}

func _ServiceInterface_Get4_HTTP_Handler(srv ServiceInterfaceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ServiceDetailIdRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationServiceInterfaceGet)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Get(ctx, req.(*ServiceDetailIdRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Service)
		return ctx.Result(200, reply)
	}
}

func _ServiceInterface_Delete4_HTTP_Handler(srv ServiceInterfaceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ServiceDetailIdRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationServiceInterfaceDelete)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Delete(ctx, req.(*ServiceDetailIdRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*common.Msg)
		return ctx.Result(200, reply)
	}
}

func _ServiceInterface_SaveServiceWorkflow0_HTTP_Handler(srv ServiceInterfaceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in Workflow
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationServiceInterfaceSaveServiceWorkflow)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SaveServiceWorkflow(ctx, req.(*Workflow))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*common.Msg)
		return ctx.Result(200, reply)
	}
}

func _ServiceInterface_GetServiceWorkflow0_HTTP_Handler(srv ServiceInterfaceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetServiceWorkflowRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationServiceInterfaceGetServiceWorkflow)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetServiceWorkflow(ctx, req.(*GetServiceWorkflowRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Workflow)
		return ctx.Result(200, reply)
	}
}

func _ServiceInterface_CreateContinuousIntegration0_HTTP_Handler(srv ServiceInterfaceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ContinuousIntegration
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationServiceInterfaceCreateContinuousIntegration)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateContinuousIntegration(ctx, req.(*ContinuousIntegration))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*common.Msg)
		return ctx.Result(200, reply)
	}
}

func _ServiceInterface_GetContinuousIntegration0_HTTP_Handler(srv ServiceInterfaceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ContinuousIntegrationDetailRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationServiceInterfaceGetContinuousIntegration)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetContinuousIntegration(ctx, req.(*ContinuousIntegrationDetailRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ContinuousIntegration)
		return ctx.Result(200, reply)
	}
}

func _ServiceInterface_GetContinuousIntegrations0_HTTP_Handler(srv ServiceInterfaceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ContinuousIntegrationsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationServiceInterfaceGetContinuousIntegrations)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetContinuousIntegrations(ctx, req.(*ContinuousIntegrationsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ContinuousIntegrations)
		return ctx.Result(200, reply)
	}
}

func _ServiceInterface_DeleteContinuousIntegration0_HTTP_Handler(srv ServiceInterfaceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ContinuousIntegrationDetailRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationServiceInterfaceDeleteContinuousIntegration)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteContinuousIntegration(ctx, req.(*ContinuousIntegrationDetailRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*common.Msg)
		return ctx.Result(200, reply)
	}
}

func _ServiceInterface_CreateContinuousDeployment0_HTTP_Handler(srv ServiceInterfaceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ContinuousDeployment
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationServiceInterfaceCreateContinuousDeployment)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateContinuousDeployment(ctx, req.(*ContinuousDeployment))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*common.Msg)
		return ctx.Result(200, reply)
	}
}

func _ServiceInterface_GetContinuousDeployment0_HTTP_Handler(srv ServiceInterfaceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ContinuousDeploymentDetailRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationServiceInterfaceGetContinuousDeployment)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetContinuousDeployment(ctx, req.(*ContinuousDeploymentDetailRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ContinuousDeployment)
		return ctx.Result(200, reply)
	}
}

func _ServiceInterface_GetContinuousDeployments0_HTTP_Handler(srv ServiceInterfaceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ContinuousDeploymentsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationServiceInterfaceGetContinuousDeployments)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetContinuousDeployments(ctx, req.(*ContinuousDeploymentsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ContinuousDeployments)
		return ctx.Result(200, reply)
	}
}

func _ServiceInterface_DeleteContinuousDeployment0_HTTP_Handler(srv ServiceInterfaceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ContinuousDeploymentDetailRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationServiceInterfaceDeleteContinuousDeployment)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteContinuousDeployment(ctx, req.(*ContinuousDeploymentDetailRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*common.Msg)
		return ctx.Result(200, reply)
	}
}

func _ServiceInterface_ApplyService0_HTTP_Handler(srv ServiceInterfaceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ApplyServiceRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationServiceInterfaceApplyService)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ApplyService(ctx, req.(*ApplyServiceRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*common.Msg)
		return ctx.Result(200, reply)
	}
}

type ServiceInterfaceHTTPClient interface {
	ApplyService(ctx context.Context, req *ApplyServiceRequest, opts ...http.CallOption) (rsp *common.Msg, err error)
	CreateContinuousDeployment(ctx context.Context, req *ContinuousDeployment, opts ...http.CallOption) (rsp *common.Msg, err error)
	CreateContinuousIntegration(ctx context.Context, req *ContinuousIntegration, opts ...http.CallOption) (rsp *common.Msg, err error)
	Delete(ctx context.Context, req *ServiceDetailIdRequest, opts ...http.CallOption) (rsp *common.Msg, err error)
	DeleteContinuousDeployment(ctx context.Context, req *ContinuousDeploymentDetailRequest, opts ...http.CallOption) (rsp *common.Msg, err error)
	DeleteContinuousIntegration(ctx context.Context, req *ContinuousIntegrationDetailRequest, opts ...http.CallOption) (rsp *common.Msg, err error)
	Get(ctx context.Context, req *ServiceDetailIdRequest, opts ...http.CallOption) (rsp *Service, err error)
	GetContinuousDeployment(ctx context.Context, req *ContinuousDeploymentDetailRequest, opts ...http.CallOption) (rsp *ContinuousDeployment, err error)
	GetContinuousDeployments(ctx context.Context, req *ContinuousDeploymentsRequest, opts ...http.CallOption) (rsp *ContinuousDeployments, err error)
	GetContinuousIntegration(ctx context.Context, req *ContinuousIntegrationDetailRequest, opts ...http.CallOption) (rsp *ContinuousIntegration, err error)
	GetContinuousIntegrations(ctx context.Context, req *ContinuousIntegrationsRequest, opts ...http.CallOption) (rsp *ContinuousIntegrations, err error)
	GetServiceWorkflow(ctx context.Context, req *GetServiceWorkflowRequest, opts ...http.CallOption) (rsp *Workflow, err error)
	List(ctx context.Context, req *ServicesRequest, opts ...http.CallOption) (rsp *Services, err error)
	Save(ctx context.Context, req *Service, opts ...http.CallOption) (rsp *common.Msg, err error)
	SaveServiceWorkflow(ctx context.Context, req *Workflow, opts ...http.CallOption) (rsp *common.Msg, err error)
}

type ServiceInterfaceHTTPClientImpl struct {
	cc *http.Client
}

func NewServiceInterfaceHTTPClient(client *http.Client) ServiceInterfaceHTTPClient {
	return &ServiceInterfaceHTTPClientImpl{client}
}

func (c *ServiceInterfaceHTTPClientImpl) ApplyService(ctx context.Context, in *ApplyServiceRequest, opts ...http.CallOption) (*common.Msg, error) {
	var out common.Msg
	pattern := "/api/v1alpha1/service/apply"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationServiceInterfaceApplyService))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ServiceInterfaceHTTPClientImpl) CreateContinuousDeployment(ctx context.Context, in *ContinuousDeployment, opts ...http.CallOption) (*common.Msg, error) {
	var out common.Msg
	pattern := "/api/v1alpha1/service/continuousdeployment"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationServiceInterfaceCreateContinuousDeployment))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ServiceInterfaceHTTPClientImpl) CreateContinuousIntegration(ctx context.Context, in *ContinuousIntegration, opts ...http.CallOption) (*common.Msg, error) {
	var out common.Msg
	pattern := "/api/v1alpha1/service/continuousintegration"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationServiceInterfaceCreateContinuousIntegration))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ServiceInterfaceHTTPClientImpl) Delete(ctx context.Context, in *ServiceDetailIdRequest, opts ...http.CallOption) (*common.Msg, error) {
	var out common.Msg
	pattern := "/api/v1alpha1/service"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationServiceInterfaceDelete))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ServiceInterfaceHTTPClientImpl) DeleteContinuousDeployment(ctx context.Context, in *ContinuousDeploymentDetailRequest, opts ...http.CallOption) (*common.Msg, error) {
	var out common.Msg
	pattern := "/api/v1alpha1/service/continuousdeployment"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationServiceInterfaceDeleteContinuousDeployment))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ServiceInterfaceHTTPClientImpl) DeleteContinuousIntegration(ctx context.Context, in *ContinuousIntegrationDetailRequest, opts ...http.CallOption) (*common.Msg, error) {
	var out common.Msg
	pattern := "/api/v1alpha1/service/continuousintegration"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationServiceInterfaceDeleteContinuousIntegration))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ServiceInterfaceHTTPClientImpl) Get(ctx context.Context, in *ServiceDetailIdRequest, opts ...http.CallOption) (*Service, error) {
	var out Service
	pattern := "/api/v1alpha1/service"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationServiceInterfaceGet))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ServiceInterfaceHTTPClientImpl) GetContinuousDeployment(ctx context.Context, in *ContinuousDeploymentDetailRequest, opts ...http.CallOption) (*ContinuousDeployment, error) {
	var out ContinuousDeployment
	pattern := "/api/v1alpha1/service/continuousdeployment"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationServiceInterfaceGetContinuousDeployment))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ServiceInterfaceHTTPClientImpl) GetContinuousDeployments(ctx context.Context, in *ContinuousDeploymentsRequest, opts ...http.CallOption) (*ContinuousDeployments, error) {
	var out ContinuousDeployments
	pattern := "/api/v1alpha1/service/continuousdeployments"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationServiceInterfaceGetContinuousDeployments))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ServiceInterfaceHTTPClientImpl) GetContinuousIntegration(ctx context.Context, in *ContinuousIntegrationDetailRequest, opts ...http.CallOption) (*ContinuousIntegration, error) {
	var out ContinuousIntegration
	pattern := "/api/v1alpha1/service/continuousintegration"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationServiceInterfaceGetContinuousIntegration))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ServiceInterfaceHTTPClientImpl) GetContinuousIntegrations(ctx context.Context, in *ContinuousIntegrationsRequest, opts ...http.CallOption) (*ContinuousIntegrations, error) {
	var out ContinuousIntegrations
	pattern := "/api/v1alpha1/service/continuousintegrations"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationServiceInterfaceGetContinuousIntegrations))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ServiceInterfaceHTTPClientImpl) GetServiceWorkflow(ctx context.Context, in *GetServiceWorkflowRequest, opts ...http.CallOption) (*Workflow, error) {
	var out Workflow
	pattern := "/api/v1alpha1/service/workflow"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationServiceInterfaceGetServiceWorkflow))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ServiceInterfaceHTTPClientImpl) List(ctx context.Context, in *ServicesRequest, opts ...http.CallOption) (*Services, error) {
	var out Services
	pattern := "/api/v1alpha1/service/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationServiceInterfaceList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ServiceInterfaceHTTPClientImpl) Save(ctx context.Context, in *Service, opts ...http.CallOption) (*common.Msg, error) {
	var out common.Msg
	pattern := "/api/v1alpha1/service"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationServiceInterfaceSave))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ServiceInterfaceHTTPClientImpl) SaveServiceWorkflow(ctx context.Context, in *Workflow, opts ...http.CallOption) (*common.Msg, error) {
	var out common.Msg
	pattern := "/api/v1alpha1/service/workflow"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationServiceInterfaceSaveServiceWorkflow))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
