services:
  redis:
    restart: unless-stopped
    ports:
      - 6379:6379
    image: redis:6.0.9
    hostname: redis
    volumes:
      - redis:/data
  mysql:
    restart: unless-stopped
    ports:
      - 3306:3306
    image: mysql:8.0
    hostname: mysql
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: ocean
      MYSQL_USER: ocean
      MYSQL_PASSWORD: ocean
  semaphore:
    restart: unless-stopped
    ports:
      - 3000:3000
    image: semaphoreui/semaphore:v2.9.4
    hostname: semaphore
    environment:
      SEMAPHORE_DB_USER: ocean
      SEMAPHORE_DB_PASS: ocean
      SEMAPHORE_DB_HOST: mysql
      SEMAPHORE_DB_PORT: 3306
      SEMAPHORE_DB_DIALECT: mysql
      SEMAPHORE_DB: ocean
      SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore/
      SEMAPHORE_ADMIN_PASSWORD: admin
      SEMAPHORE_ADMIN_NAME: admin
      SEMAPHORE_ADMIN_EMAIL: admin@localhost
      SEMAPHORE_ADMIN: admin
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: gs72mPntFATGJs9qK0pQ0rKtfidlexiMjYCH9gWKhTU=
      SEMAPHORE_LDAP_ACTIVATED: 'no'
      SEMAPHORE_LDAP_HOST: ''
      SEMAPHORE_LDAP_PORT: ''
      SEMAPHORE_LDAP_NEEDTLS: ''
      SEMAPHORE_LDAP_DN_BIND: ''
      SEMAPHORE_LDAP_PASSWORD: ''
      SEMAPHORE_LDAP_DN_SEARCH: ''
      SEMAPHORE_LDAP_SEARCH_FILTER: ''
    depends_on:
      - mysql
  ocean:
    restart: unless-stopped
    ports:
      - 8000:8000
      - 9000:9000
    image: frambos/ocean:0.0.1
    hostname: ocean
    environment:
      HTTP_NETWORK: 
      HTTP_ADDR: 
      GRPC_NETWORK: 
      GRPC_ADDR: 
      DATABASE_DRIVER: mysql
      DATABASE_USERNAME: ocean
      DATABASE_PASSWORD: ocean
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_DATABASE: ocean
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: 
      REDIS_DB: 0
      SEMAPHORE_ADMIN: admin
      SEMAPHORE_ADMIN_PASSWORD: admin
      SEMAPHORE_HOST: semaphore
      SEMAPHORE_PORT: 3000
      KUBERNETES_MASTER_URL: 
      KUBERNETES_KUBE_CONFIG: 
    depends_on:
      - semaphore
      - mysql
      - redis
volumes:
  mysql:
  redis: