apiVersion: v1
kind: Namespace
metadata:
  name: ocean-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ocean-app-service-account
  namespace: ocean-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ocean-app-cluster-admin-binding
subjects:
  - kind: ServiceAccount
    name: ocean-app-service-account
    namespace: ocean-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocean-app
  namespace: ocean-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocean-app
  template:
    metadata:
      labels:
        app: ocean-app
    spec:
      serviceAccountName: ocean-app-service-account
      hostNetwork: true
      containers:
        - name: ocean-app-container
          image: ocean:v0.0.1
          ports:
            - containerPort: 80
            - containerPort: 8080
