---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-autoscaler-cloud-config
  namespace: kube-system
data:
  cloud-config: |-
    address: "testserver-multiport-service.default.svc.cluster.local:9000"
