// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/f-rambo/cloud-copilot/infrastructure"
	"github.com/f-rambo/cloud-copilot/internal/biz"
	"github.com/f-rambo/cloud-copilot/internal/conf"
	"github.com/f-rambo/cloud-copilot/internal/data"
	"github.com/f-rambo/cloud-copilot/internal/interfaces"
	"github.com/f-rambo/cloud-copilot/internal/server"
	"github.com/f-rambo/cloud-copilot/runtime"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "github.com/joho/godotenv/autoload"
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(contextContext context.Context, bootstrap *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(bootstrap, logger)
	if err != nil {
		return nil, nil, err
	}
	clusterData := data.NewClusterRepo(dataData, logger)
	baremetal := infrastructure.NewBaremetal(bootstrap, logger)
	aliCloudUsecase := infrastructure.NewAliCloudUseCase(bootstrap, logger)
	awsCloudUsecase := infrastructure.NewAwsCloudUseCase(bootstrap, logger)
	clusterInfrastructure := infrastructure.NewInfrastructure(bootstrap, baremetal, aliCloudUsecase, awsCloudUsecase, logger)
	clusterRuntime := runtime.NewClusterRuntime(bootstrap, logger)
	clusterUsecase, err := biz.NewClusterUseCase(contextContext, bootstrap, clusterData, clusterInfrastructure, clusterRuntime, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	clusterInterface := interfaces.NewClusterInterface(clusterUsecase, bootstrap, logger)
	appData := data.NewAppRepo(dataData, logger)
	appRuntime := runtime.NewAppRuntime(logger)
	appUsecase := biz.NewAppUsecase(appData, appRuntime, logger, bootstrap)
	userData := data.NewUserRepo(dataData, bootstrap, logger)
	userUseCase := biz.NewUseUser(userData, logger, bootstrap)
	appInterface := interfaces.NewAppInterface(appUsecase, userUseCase, logger)
	servicesData := data.NewServicesRepo(dataData, logger)
	serviceRuntime := runtime.NewServiceRuntime(logger)
	workflowRuntime := runtime.NewWorkflowRuntime(logger)
	servicesUseCase := biz.NewServicesUseCase(servicesData, serviceRuntime, workflowRuntime, logger)
	servicesInterface := interfaces.NewServicesInterface(servicesUseCase)
	userInterface := interfaces.NewUserInterface(userUseCase, bootstrap)
	workspaceData := data.NewWorkspaceRepo(dataData, logger)
	workspaceUsecase := biz.NewWorkspaceUsecase(workspaceData, logger)
	workspaceInterface := interfaces.NewWorkspaceInterface(workspaceUsecase, logger)
	projectData := data.NewProjectRepo(dataData, bootstrap, logger)
	projectRuntime := runtime.NewProjectRuntime(logger)
	projectUsecase := biz.NewProjectUseCase(projectData, projectRuntime, logger, bootstrap)
	projectInterface := interfaces.NewProjectInterface(projectUsecase, userUseCase, bootstrap, logger)
	grpcServer := server.NewGRPCServer(bootstrap, clusterInterface, appInterface, servicesInterface, userInterface, workspaceInterface, projectInterface, logger)
	httpServer := server.NewHTTPServer(bootstrap, clusterInterface, appInterface, servicesInterface, userInterface, workspaceInterface, projectInterface, logger)
	bizBiz := biz.NewBiz(clusterUsecase, appUsecase)
	app := newApp(contextContext, logger, grpcServer, httpServer, bizBiz)
	return app, func() {
		cleanup()
	}, nil
}
