// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.7.2
// - protoc             v5.27.1
// source: api/user/v1alpha1/user.proto

package v1alpha1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationUserInterfaceDeleteUser = "/user.v1alpha1.UserInterface/DeleteUser"
const OperationUserInterfaceGetUserInfo = "/user.v1alpha1.UserInterface/GetUserInfo"
const OperationUserInterfaceGetUsers = "/user.v1alpha1.UserInterface/GetUsers"
const OperationUserInterfaceSaveUser = "/user.v1alpha1.UserInterface/SaveUser"
const OperationUserInterfaceSignIn = "/user.v1alpha1.UserInterface/SignIn"

type UserInterfaceHTTPServer interface {
	DeleteUser(context.Context, *User) (*Msg, error)
	GetUserInfo(context.Context, *emptypb.Empty) (*User, error)
	GetUsers(context.Context, *UsersRequest) (*Users, error)
	SaveUser(context.Context, *User) (*User, error)
	SignIn(context.Context, *SignIn) (*User, error)
}

func RegisterUserInterfaceHTTPServer(s *http.Server, srv UserInterfaceHTTPServer) {
	r := s.Route("/")
	r.POST("/api/v1alpha1/user/signin", _UserInterface_SignIn0_HTTP_Handler(srv))
	r.GET("/api/v1alpha1/user", _UserInterface_GetUserInfo0_HTTP_Handler(srv))
	r.GET("/api/v1alpha1/users", _UserInterface_GetUsers0_HTTP_Handler(srv))
	r.POST("/api/v1alpha1/user", _UserInterface_SaveUser0_HTTP_Handler(srv))
	r.DELETE("/api/v1alpha1/user", _UserInterface_DeleteUser0_HTTP_Handler(srv))
}

func _UserInterface_SignIn0_HTTP_Handler(srv UserInterfaceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SignIn
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserInterfaceSignIn)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SignIn(ctx, req.(*SignIn))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*User)
		return ctx.Result(200, reply)
	}
}

func _UserInterface_GetUserInfo0_HTTP_Handler(srv UserInterfaceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserInterfaceGetUserInfo)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetUserInfo(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*User)
		return ctx.Result(200, reply)
	}
}

func _UserInterface_GetUsers0_HTTP_Handler(srv UserInterfaceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UsersRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserInterfaceGetUsers)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetUsers(ctx, req.(*UsersRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Users)
		return ctx.Result(200, reply)
	}
}

func _UserInterface_SaveUser0_HTTP_Handler(srv UserInterfaceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in User
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserInterfaceSaveUser)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SaveUser(ctx, req.(*User))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*User)
		return ctx.Result(200, reply)
	}
}

func _UserInterface_DeleteUser0_HTTP_Handler(srv UserInterfaceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in User
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserInterfaceDeleteUser)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteUser(ctx, req.(*User))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Msg)
		return ctx.Result(200, reply)
	}
}

type UserInterfaceHTTPClient interface {
	DeleteUser(ctx context.Context, req *User, opts ...http.CallOption) (rsp *Msg, err error)
	GetUserInfo(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *User, err error)
	GetUsers(ctx context.Context, req *UsersRequest, opts ...http.CallOption) (rsp *Users, err error)
	SaveUser(ctx context.Context, req *User, opts ...http.CallOption) (rsp *User, err error)
	SignIn(ctx context.Context, req *SignIn, opts ...http.CallOption) (rsp *User, err error)
}

type UserInterfaceHTTPClientImpl struct {
	cc *http.Client
}

func NewUserInterfaceHTTPClient(client *http.Client) UserInterfaceHTTPClient {
	return &UserInterfaceHTTPClientImpl{client}
}

func (c *UserInterfaceHTTPClientImpl) DeleteUser(ctx context.Context, in *User, opts ...http.CallOption) (*Msg, error) {
	var out Msg
	pattern := "/api/v1alpha1/user"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationUserInterfaceDeleteUser))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *UserInterfaceHTTPClientImpl) GetUserInfo(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*User, error) {
	var out User
	pattern := "/api/v1alpha1/user"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationUserInterfaceGetUserInfo))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *UserInterfaceHTTPClientImpl) GetUsers(ctx context.Context, in *UsersRequest, opts ...http.CallOption) (*Users, error) {
	var out Users
	pattern := "/api/v1alpha1/users"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationUserInterfaceGetUsers))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *UserInterfaceHTTPClientImpl) SaveUser(ctx context.Context, in *User, opts ...http.CallOption) (*User, error) {
	var out User
	pattern := "/api/v1alpha1/user"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationUserInterfaceSaveUser))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *UserInterfaceHTTPClientImpl) SignIn(ctx context.Context, in *SignIn, opts ...http.CallOption) (*User, error) {
	var out User
	pattern := "/api/v1alpha1/user/signin"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationUserInterfaceSignIn))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
