ansible:
  ssh_connection:
    pipelining: true
    ansible_ssh_args: '-o ControlMaster=auto -o ControlPersist=30m -o ConnectionAttempts=100 -o UserKnownHostsFile=/dev/null'
  defaults:
    timeout: 300
    ask_pass: false
    ask_become_pass: false
    force_valid_group_names: ignore
    host_key_checking: false
    gathering: smart
    fact_caching: jsonfile
    fact_caching_connection: /tmp
    fact_caching_timeout: 86400
    stdout_callback: default
    display_skipped_hosts: no
    library: './library'
    callbacks_enabled: 'profile_tasks,ara_default'
    roles_path: 'roles:$VIRTUAL_ENV/usr/local/share/kubespray/roles:$VIRTUAL_ENV/usr/local/share/ansible/roles:/usr/share/kubespray/roles'
    deprecation_warnings: false
    inventory_ignore_extensions: '~, .orig, .bak, .ini, .cfg, .retry, .pyc, .pyo, .creds, .gpg'
  inventory:
    ignore_patterns: 'artifacts, credentials'