apiVersion: kubeadm.k8s.io/v1beta4
kind: ClusterConfiguration
clusterName: "{CLUSTER_NAME}"
kubernetesVersion: "{CLUSTER_VERSION}"
certificatesDir: "/etc/kubernetes/pki"
imageRepository: "{IMAGE_REPO}"
controlPlaneEndpoint: "{MASTER_IP}:6443"
etcd:
  local:
    imageRepository: "{IMAGE_REPO}"
networking:
  serviceSubnet: "10.96.0.0/12"
  podSubnet: "10.244.0.0/16"
  dnsDomain: "{CLUSTER_NAME}"
