env: local
server:
  name: ocean
  http:
    network: tcp
    addr: 0.0.0.0:8000
  static:
    network: tcp
    addr: 0.0.0.0:8080
  grpc:
    network: tcp
    addr: 0.0.0.0:9000
data:
  driver: sqlite
  host: localhost
  port: 3306
  username: root
  password: '123456'
  database: ocean
  dbfilepath: 'resource/db/gorm.db'
etcd:
  username: ''
  password: ''
  endpoints:
    - ''
log:
  path: logs
  filename: log.log
  max_size: 500
  max_backups: 3
  max_age: 28
  compress: true
  local_time: true
auth:
  exp: 24
  key: 'ocean'
  email: 'admin@admin.com'
  password: '123456qwe'
resource:
  app: 'resource/app/'
  icon: 'resource/icon/'
  repo: 'resource/repo/'
  cluster: 'resource/cluster/'
  kubespray_url: 'https://github.com/kubernetes-sigs/kubespray/archive/refs/tags/v2.22.0.tar.gz'
  ansible_cli: '/Users/yangzongfang/anaconda3/envs/ansible/bin/ansible-playbook'
  pulumi_path: '~/.pulumi'
business:
  - name: 'Backend'
    technologys:
      - name: 'golang'
      - name: 'java'
      - name: 'python'
  - name: 'Frontend'
    technologys:
      - name: 'vue'
      - name: 'react'
  - name: 'BigData'
    technologys:
      - name: 'hadoop'
      - name: 'spark'
  - name: 'AI'
    technologys:
      - name: 'tensorflow'
      - name: 'pytorch'
ansible:
  ssh_connection:
    pipelining: true
    ansible_ssh_args: '-o ControlMaster=auto -o ControlPersist=30m -o ConnectionAttempts=100 -o UserKnownHostsFile=/dev/null'
  defaults:
    timeout: 300
    ask_pass: false
    ask_become_pass: false
    force_valid_group_names: ignore
    host_key_checking: false
    gathering: smart
    fact_caching: jsonfile
    fact_caching_connection: /tmp
    fact_caching_timeout: 86400
    stdout_callback: default
    display_skipped_hosts: no
    library: './library'
    callbacks_enabled: 'profile_tasks'
    roles_path: 'roles:$VIRTUAL_ENV/usr/local/share/kubespray/roles:$VIRTUAL_ENV/usr/local/share/ansible/roles:/usr/share/kubespray/roles'
    deprecation_warnings: false
    inventory_ignore_extensions: '~, .orig, .bak, .ini, .cfg, .retry, .pyc, .pyo, .creds, .gpg'
  inventory:
    ignore_patterns: 'artifacts, credentials'