server:
  name: ocean
  http:
    network: tcp
    addr: 0.0.0.0:8000
  static:
    network: tcp
    addr: 0.0.0.0:8080
  grpc:
    network: tcp
    addr: 0.0.0.0:9000
data:
  database:
    driver: 
    host: localhost
    port: 3306
    username: root
    password: '123456'
    database: ocean
    dbfilepath: '/tmp/gorm.db'
kubernetes:
  master_url: 
  kube_config: 
  namespace: default
log:
  path: logs
  filename: log.log
  max_size: 500
  max_backups: 3
  max_age: 28
  compress: true
  local_time: true
auth:
  exp: 24
  key: 'ocean'
  email: 'admin'
  password: '123.456a'
resource:
  app_path: 'resource/app/'
  icon_path: 'resource/icon/'
  repo_path: 'resource/repo/'