server:
  debug: false
  env: local
  name: ocean
  version: 0.0.1
  http:
    network: tcp
    addr: 0.0.0.0:8000
  grpc:
    network: tcp
    addr: 0.0.0.0:9000
data:
  driver: sqlite
  database: ocean
  host: ""
  port: 3306
  username: ""
  password: ""
log:
  max_size: 500
  max_backups: 3
  max_age: 28
auth:
  exp: 24
  key: "S89XMkyGIpI0tgJkf7b8undK"
  adminpassword: "123456"
app:
  - name: base
    version: 1.24.0
    namespace: istio-system
  - name: istiod
    version: 1.24.0
    namespace: istio-system
  - name: cni
    version: 1.24.0
    namespace: istio-system
  - name: ztunnel
    version: 1.24.0
    namespace: istio-system
  - name: gateway
    version: 1.24.0
    namespace: istio-ingress