server:
  http:
    network: tcp
    addr: 0.0.0.0:8000
  grpc:
    network: tcp
    addr: 0.0.0.0:9000
data:
  database:
    driver: mysql
    host: localhost
    port: 3306
    username: root
    password: '123456'
    database: ocean
  redis:
    host: localhost
    port: 6379
    password:
    db: 0
  semaphore:
    admin: admin
    admin_password: 'changeme'
    host: localhost
    port: 3000
  kubernetes:
    master_url: 
    kube_config: 
log:
  path: logs
  filename: log.log
  max_size: 500
  max_backups: 3
  max_age: 28
  compress: true
  local_time: true
auth:
  exp: 24
  key: 'ocean'
  email: 'admin'
  password: '123456'