server:
  name: cloud-copilot
  version: "0.0.1"
  http:
    network: tcp
    addr: 0.0.0.0:8000
    timeout: 15
  grpc:
    network: tcp
    addr: 0.0.0.0:9000
    timeout: 15
services:
  - name: cluster-runtime
    version: "0.0.1"
    port: 9003
    addr: localhost
    timeout: 15
  - name: infrastructure
    version: "0.0.1"
    port: 9002
    addr: localhost
    timeout: 15
  - name: sidecar
    version: "0.0.1"
    port: 9001
    addr: localhost
    timeout: 15
data:
  database: cloud-copilot
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "123456"
log:
  max_size: 500
  max_backups: 3
  max_age: 28
auth:
  exp: 24
  key: "S89XMkyGIpI0tgJkf7b8undK"
  admin_email: "admin@eamil.com"
  admin_password: "123456"
cluster:
  name: "cloud-copilot"
  env: local
  level:
    basic: 50
    advanced: 100
    standard: 200
  ingress_rules:
    - name: "apiserver"
      start_port: 6443
      end_port: 6443
      protocol: "TCP"
      ip_cidr: "0.0.0.0/0"
      access: 0
    - name: "kubelet"
      start_port: 10250
      end_port: 10255
      protocol: "TCP"
      ip_cidr: "0.0.0.0/0"
      access: 0
    - name: "ssh"
      start_port: 22
      end_port: 22
      protocol: "TCP"
      ip_cidr: "0.0.0.0/0"
      access: 0
    - name: "https"
      start_port: 443
      end_port: 443
      protocol: "TCP"
      ip_cidr: "0.0.0.0/0"
      access: 1
    - name: "http"
      start_port: 80
      end_port: 80
      protocol: "TCP"
      ip_cidr: "0.0.0.0/0"
      access: 1
