server:
  name: cloud-copilot
  version: "0.0.1"
  http:
    network: tcp
    addr: 0.0.0.0:8000
    timeout: 15
  grpc:
    network: tcp
    addr: 0.0.0.0:9000
    timeout: 15
data:
  database: cloud-copilot
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "123456"
log:
  max_size: 500
  max_backups: 3
  max_age: 28
auth:
  exp: 24
  key: "S89XMkyGIpI0tgJkf7b8undK"
  admin_email: "admin@eamil.com"
  admin_password: "123456"
cluster:
  name: "cloud-copilot"
  kubernetes_version: "v1.31.2"
  containerd_version: "v2.0.0"
  runc_version: "v1.2.1"
  image_repository: "registry.aliyuncs.com/google_containers"
  level:
    basic: 50
    advanced: 100
    standard: 200
  nodegroup_config:
    cpu: 2
    memory: 4
    disk_size: 30
    target_size: 1
    min_size: 1
    max_size: 1
  ingress_rules:
    - name: "apiserver"
      start_port: 6443
      end_port: 6443
      protocol: "TCP"
      ip_cidr: "0.0.0.0/0"
      access: false
    - name: "kubelet"
      start_port: 10250
      end_port: 10255
      protocol: "TCP"
      ip_cidr: "0.0.0.0/0"
      access: false
    - name: "ssh"
      start_port: 22
      end_port: 22
      protocol: "TCP"
      ip_cidr: "0.0.0.0/0"
      access: false
    - name: "https"
      start_port: 443
      end_port: 443
      protocol: "TCP"
      ip_cidr: "0.0.0.0/0"
      access: true
    - name: "http"
      start_port: 80
      end_port: 80
      protocol: "TCP"
      ip_cidr: "0.0.0.0/0"
      access: true
