server:
  name: cloud-copilot
  version: "0.0.1"
  env: jump # local, jump, prod
  http:
    network: tcp
    addr: 0.0.0.0:8000
  grpc:
    network: tcp
    addr: 0.0.0.0:9000
data:
  database: cloudcopilot
log:
  max_size: 500
  max_backups: 3
  max_age: 28
auth:
  exp: 24
  key: "S89XMkyGIpI0tgJkf7b8undK"
  admin_email: "admin@email.com"
  admin_password: "admin@email.com"
infrastructure:
  shell: "shell"
  resource: "resource"
  component: "component"
  cluster: ""
