ocean:  
  server:
    name: ocean
    http:
      network: tcp
      addr: 0.0.0.0:8000
    static:
      network: tcp
      addr: 0.0.0.0:8080
    grpc:
      network: tcp
      addr: 0.0.0.0:9000
  data:
    driver: sqlite
    host: localhost
    port: 3306
    username: root
    password: '123456'
    database: ocean
    dbfilepath: 'resource/db/gorm.db'
  log:
    path: logs
    filename: log.log
    max_size: 500
    max_backups: 3
    max_age: 28
    compress: true
    local_time: true
  auth:
    exp: 24
    key: 'ocean'
    email: 'admin@admin.com'
    password: '123456qwe'
  resource:
    app: 'resource/app/'
    icon: 'resource/icon/'
    repo: 'resource/repo/'
    cluster: 'resource/cluster/'
    kubespray_url: 'https://github.com/kubernetes-sigs/kubespray/archive/refs/tags/v2.22.0.tar.gz'
    ansible_cli: '/Users/yangzongfang/anaconda3/envs/ansible/bin/ansible-playbook'
  business:
    - name: 'Backend'
      technologys:
        - name: 'golang'
        - name: 'java'
        - name: 'python'
    - name: 'Frontend'
      technologys:
        - name: 'vue'
        - name: 'react'
    - name: 'BigData'
      technologys:
        - name: 'hadoop'
        - name: 'spark'
    - name: 'AI'
      technologys:
        - name: 'tensorflow'
        - name: 'pytorch'

