apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: example-daemonset
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: example-daemonset
  template:
    metadata:
      labels:
        app: example-daemonset
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: example-container
        image: your-image:latest
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
        volumeMounts:
        - name: host-volume
          mountPath: /path/in/container
      volumes:
      - name: host-volume
        hostPath:
          path: /path/on/host
          type: Directory
