// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"ocean/internal/biz"
	"ocean/internal/conf"
	"ocean/internal/data"
	"ocean/internal/server"
	"ocean/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo, logger)
	greeterService := service.NewGreeterService(greeterUsecase)
	getInfraRepo := data.NewInfraRepo(dataData, logger)
	infraUsecase := biz.NewInfraUseCase(getInfraRepo, logger)
	infraService := service.NewInfraService(infraUsecase)
	clusterRepo := data.NewClusterRepo(dataData, logger)
	clusterUsecase := biz.NewClusterUseCase(clusterRepo, logger)
	clusterService := service.NewClusterService(clusterUsecase)
	appRepo := data.NewAppRepo(dataData, logger)
	appUsecase := biz.NewAppUsecase(appRepo, logger)
	appService := service.NewAppService(appUsecase)
	grpcServer := server.NewGRPCServer(confServer, greeterService, infraService, clusterService, appService, logger)
	httpServer := server.NewHTTPServer(confServer, greeterService, infraService, clusterService, appService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
