apiVersion: kubeadm.k8s.io/v1beta4
kind: ClusterConfiguration
clusterName: "{{.Name}}"
kubernetesVersion: "{{.KubernetesVersion}}"
certificatesDir: "/etc/kubernetes/pki"
imageRepository: "{{.ImageRepository}}"
dns:
  disabled: false
proxy:
  disabled: true
apiServer:
  certSANs:
    - "{{.ApiServerAddress}}"
controlPlaneEndpoint: "{{.ApiServerAddress}}:6443"
networking:
  serviceSubnet: "{{.ServiceCidr}}"
  podSubnet: "{{.PodCidr}}"
  dnsDomain: "{{.Domain}}"
